### ISSUE TITLE
can't find header files for ruby at /usr/share/include/ruby.h

### ISSUE THREAD

**Issue by Tusko** [petethepig/marmot#6]
Здраствуйте Дмитрий. Подскажите, что делать с такой штукой?
Никогда до этого не работал с руби 

     Building native extensions.  This could take a while...  
      ERROR:  Error installing marmot:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb 
    mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

    Gem files will remain installed in /usr/local/share/gems/gems/json-1.8.3 for inspection.
    Results logged to /usr/local/share/gems/gems/json-1.8.3/ext/json/ext/generator/gem_make.out

**Comment by Tusko** [comment]
Centos 7
gem -v  --> 2.0.14

**Comment by petethepig** [comment]
Ух, сложно сказать. Посмотрите, что пишет в файле `/usr/local/share/gems/gems/json-1.8.3/ext/json/ext/generator/gem_make.out`

**Comment by Tusko** [comment]
@petethepig 

/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

**Comment by petethepig** [comment]
Может быть это поможет:
```
yum install ruby-devel
```

**Comment by Tusko** [comment]
@petethepig 7 gems installed
спасибо большое)
